[package]
name = "pdf_composer"
version = "0.1.0"
edition = "2021"
description = "Crate to create PDF documents from YAML Front Matter source documents"
authors = ["OrangeKiwi", "Richard Locke"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/orangekiwi-io/pdf_composer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
dotenvy = "0.15.7"
headless_chrome = "1.0.9"
lopdf = "0.32.0"
markdown = "0.3.0"
regex = "1.10.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_yaml = "0.9.33"
url-escape = "0.1.1"
